### ISSUE TITLE
feat: hide llama.cpp logs

### ISSUE THREAD

**Issue by ExposedCat** [withcatai/node-llama-cpp#106]
### Feature Description

Hide all the logs produced by llama.cpp about model running/parameters/etc

### The Solution

Either ignore output or process it and receive as a callback when running model internally

### Considered Alternatives

In general non-optional logging in (any) libraries is a bad practice

### Additional Context

Thanks for your work ❤️ 

### Related Features to This Feature Request

- [ ] Metal support
- [ ] CUDA support
- [ ] Grammar

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, and I know how to start.

**Comment by giladgd** [comment]
I already plan to try to do it as part of v3 (#105)

This library depends on `llama.cpp`'s support for disabling logs.
As far as I've seen, it's possible to disable the logs of `llama.cpp` with a specific build flag, so I think I'll then add a flag to the `download` and `build` commands to enable logs, and disable it by default.
