### ISSUE TITLE
bug: model parameter `threads` doesn't work

### ISSUE THREAD

**Issue by pafik13** [withcatai/node-llama-cpp#114]
### Issue description

It seems to me that parameter `threads` doesn't work as expected

### Expected Behavior

If I have 24 CPUs and pass `threads:24` then all CPUs should be utilized. II tried call original `llama.cpp` with argument `-t 24` and it works normally as expected.

### Actual Behavior

I pass parameter `thread: 24 or 1` to constructor and nothing is changed: always it starts utilize 4 CPUs upper 80% and sometimes use 1-2 additional with 25-50% utilization.

### Steps to reproduce

Try to pass different `threads` value to model constructor and observe CPUs utilization (for example, `htop`)

### My Environment

| Dependency               | Version             |
| ---                      | ---                 |
| Operating System         |       Ubuntu 22.04.3 LTS              |
| CPU                      | AMD EPYC 7742 64-Core Processor |
| Node.js version          | v20.10.0            |
| Typescript version       | no use            |
| `node-llama-cpp` version | 3.0.0-beta.1 &   v2.8.1         |

### Additional Context

`./llama.cpp/main -m ./catai/models/phind-codellama-34b-q3_k_s -p "Please, write JavaScript function to sort array" -ins -t 24`

![Screenshot from 2023-12-07 23-03-02](https://github.com/withcatai/node-llama-cpp/assets/5254026/82923f47-c213-4cd0-a08f-112fdfd9095d)

```
const model = new LlamaModel({
    modelPath: "/root/catai/models/phind-codellama-34b-q3_k_s",
    threads: 1,
});
```

![Screenshot from 2023-12-07 23-04-41](https://github.com/withcatai/node-llama-cpp/assets/5254026/74351121-6079-495c-a3f1-58411cf1d3fa)

```
const model = new LlamaModel({
    modelPath: "/root/catai/models/phind-codellama-34b-q3_k_s",
    threads: 24,
});
```

![Screenshot from 2023-12-07 23-05-59](https://github.com/withcatai/node-llama-cpp/assets/5254026/d447dfa1-2308-4c00-9649-c72d930c6852)

### Relevant Features Used

- [ ] Metal support
- [ ] CUDA support
- [ ] Grammar

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, but I don't know how to start. I would need guidance.

**Comment by giladgd** [comment]
@pafik13 Thanks for the detailed issue, it helped me a lot to investigate this problem :)
I found the bug, I'll include the fix for it in the next beta

**Comment by stewartoallen** [comment]
@giladgd can you point me to where you found the problem? if I can fix it locally, I can submit a PR.
