### ISSUE TITLE
No CUDA toolset found Error even its Found CUDAToolkit

### ISSUE THREAD

**Issue by sooraj007** [withcatai/node-llama-cpp#122]
### Issue description

when try to build for cuda build is failing its showing cublas and cudatoolkit found but still it failed showing No Cuda toolset found, i have added all the necessory envirnment variables but stil failing

### Expected Behavior

I am using cuda toolkit version 12.2 and visual studio 2022 community edition , when i try to build it supposed to be build but it shows error

Expecting to build

### Actual Behavior

Its now showing error like this using this command npx --no node-llama-cpp download --cuda
env variables : NODE_LLAMA_CPP_CMAKE_OPTION_CMAKE_GENERATOR_TOOLSET : v143
this is one of the env variable that is i thin kproblamatic , above one is using for visual studio , its only working when i give like above
but dont know if the same using when cmake build

-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - not found
-- Found Threads: TRUE
-- Found CUDAToolkit: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.2/include (found version "12.2.91")
-- cuBLAS found
CMake Error at xpack/store/@xpack-dev-tools/cmake/3.26.5-1.1/.content/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:501 (message):
  No CUDA toolset found.
Call Stack (most recent call first):
  xpack/store/@xpack-dev-tools/cmake/3.26.5-1.1/.content/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:8 (CMAKE_DETERMINE_COMPILER_ID_BUILD)

### Steps to reproduce

just run npx --no node-llama-cpp download --cuda
then its hapening

### My Environment

| Dependency               | Version             |
| ---                      | ---                 |
| Operating System       windows  |                     |
| CPU                      | Intel i9 -13900k |
| Node.js version          | x.y.zzz             |
| Typescript version       | x.y.zzz             |
| `node-llama-cpp` version | 3.0.0-beta.1            |

### Relevant Features Used

- [ ] Metal support
- [X] CUDA support
- [ ] Grammar

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, and I know how to start.

**Comment by sooraj007** [comment]
@awijshoff 

Thanks bro, that worked out great, it would be great if author should mention these steps also in the documentation, i was searching it for 2 days.
Again thanks

**Comment by giladgd** [comment]
@sooraj007 For the issues that cannot be solved by `node-llama-cpp` automatically, I've added a section of issues and solutions in [CUDA documentation](https://withcatai.github.io/node-llama-cpp/guide/CUDA); it would be great if you could add there the details of the issue you faced and its solution.

You can create a PR by clicking on the "Edit this page" button at the bottom of the page.
