### ISSUE TITLE
other people's gguf file can not run

### ISSUE THREAD

**Issue by xuedaobian** [withcatai/node-llama-cpp#124]
### Issue description

error loading model: unknown model architecture: ''

### Expected Behavior

While I was browsing Reddit, I found a GGUF model of phi-2 trained by others，but when i download the model from the repository ，it can not run 。

the reddit page: https://www.reddit.com/r/LocalLLaMA/comments/18hnhd6/tutorial_how_to_run_phi2_locally_or_on_colab_for/?rdt=58275

the resposity addr: https://huggingface.co/radames/phi-2-quantized/tree/main

when i execution `npx --no node-llama-cpp chat --model ./models/model-v2-qk4.gguf`  and `npx --no node-llama-cpp chat --model ./models/model-v2-q80.gguf`, the error appear.

### Actual Behavior

<img width="1123" alt="image" src="https://github.com/withcatai/node-llama-cpp/assets/38198170/93ab9433-0937-4d76-b5b6-b3249a205137">

in this image, mistral-xxx is can run successful, it from thebloke

### Steps to reproduce

<img width="211" alt="image" src="https://github.com/withcatai/node-llama-cpp/assets/38198170/8ed775ff-b10e-41e7-9b1d-6217f0f33618">

i just run simple commands from getting started part, those included by 
npx --no node-llama-cpp chat --model <path-to-a-model-file-on-your-computer>
and
node index.js(code from getting stared part)

### My Environment

| Dependency               | Version             |
| ---                      | ---                 |
| Operating System         |                     |
| CPU                      |  Apple M1 |
| Node.js version          | 18.16.0            |
| Typescript version       | use javascript             |
| `node-llama-cpp` version | 2.8.2        |

### Additional Context

i dont kow how to dstinguish which model can be run, its so hard

thank you receive

### Relevant Features Used

- [ ] Metal support
- [ ] CUDA support
- [ ] Grammar

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, and I know how to start.

**Comment by giladgd** [comment]
@xuedaobian There's something weird with this particular model that you tried, as I see there are multiple parts for each file, and I haven't seen GGUF model files like that before.

I think you better try to use this one instead:
https://huggingface.co/kroonen/phi-2-GGUF/tree/main

**Comment by xuedaobian** [comment]
thank you @giladgd ,i visited the link of you sent, it's useful!
