### ISSUE TITLE
Bun support

### ISSUE THREAD

**Issue by mnlttt** [withcatai/node-llama-cpp#152]
### Feature Description

Currently, running the library using [Bun](https://bun.sh/) throws an error:

![CleanShot 2024-01-29 at 10 10 56@2x](https://github.com/withcatai/node-llama-cpp/assets/37709016/9d49003e-b1dd-4e9f-ba16-982f1d712ae4)

Is this Bun's fault or something else?

### The Solution

It should run like NodeJS

### Considered Alternatives

Well, don't use Bun?

### Related Features to This Feature Request

- [ ] Metal support
- [ ] CUDA support
- [ ] Grammar

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, and I know how to start.

**Comment by giladgd** [comment]
@mnlttt From my tests, `node-llama-cpp` works great on bun, so I think there's some misconfiguration in your environment, or your bun version is not up-to-date
