### ISSUE TITLE
Cannot instantiate new LlamaModel bc class constructor was changed to private in beta

### ISSUE THREAD

**Issue by convertsee-dev** [withcatai/node-llama-cpp#200]
### Issue description

The constructor was changed to private so we cannot use this in TypeScript.

### Expected Behavior

I should  be able to follow docs:
```
const model = new LlamaModel({
    modelPath: path.join(__dirname, "models", "codellama-13b.Q3_K_M.gguf")
});
```

### Actual Behavior

I get an error: Constructor of class 'LlamaModel' is private and only accessible within the class declaration.ts(2673)

### Steps to reproduce

npm i node-llama-cpp@beta and attempt to follow docs to instantiate a new LlamaModel:
```
const model = new LlamaModel({
    modelPath: path.join(__dirname, "models", "codellama-13b.Q3_K_M.gguf")
});
```

### My Environment

| Dependency               | Version             |
| ---                      | ---                 |
| Operating System         |      Windows               |
| CPU                      | Intel i9 / Apple M1 |
| Node.js version          | 20             |
| Typescript version       | 5.2             |
| `node-llama-cpp` version | beta             |

### Relevant Features Used

- [ ] Metal support
- [ ] CUDA support
- [ ] Grammar

### Are you willing to resolve this issue by submitting a Pull Request?

No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by brandon-e2e** [comment]
This is not a bug. The beta docs specifically state how to create a model: https://github.com/withcatai/node-llama-cpp/pull/105

```
const llama = await getLlama();
const model = await llama.loadModel({
    modelPath: path.join(__dirname, "models", "dolphin-2.1-mistral-7b.Q4_K_M.gguf")
});
```

**Comment by convertsee-dev** [comment]
Thank you for your response, really appreciate it.

**Comment by giladgd** [comment]
@convertsee-dev The solution was given by @brandon-e2e in this ticket already, so I closed it as completed
