### ISSUE TITLE
Support for Llama 3

### ISSUE THREAD

**Issue by clvnthe04** [withcatai/node-llama-cpp#207]
### Feature Description

Llama 3 support

### The Solution

Allow for llama 3 support

### Considered Alternatives

na

### Related Features to This Feature Request

- [ ] Metal support
- [ ] CUDA support
- [ ] Grammar

### Are you willing to resolve this issue by submitting a Pull Request?

No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by giladgd** [comment]
Llama 3 is already supported in [version 3 beta](https://github.com/withcatai/node-llama-cpp/pull/105)
