### ISSUE TITLE
Error  node-llama-cpp build

### ISSUE THREAD

**Issue by loretoparisi** [withcatai/node-llama-cpp#24]
I have manually downloaded in a container `llama.cpp` and set the env:

```Dockerfile
ENV NODE_LLAMA_CPP_REPO_RELEASE /app/llama.cpp
RUN cd $ROOT_APPLICATION && git clone https://github.com/ggerganov/llama.cpp.git
```
so in the container the env is correct, but when I try to build:
```bash
root@981b3099966c:/app# echo $NODE_LLAMA_CPP_REPO_RELEASE
/app/llama.cpp
root@981b3099966c:/app# npx --yes node-llama-cpp build --nodeTarget $NODE_VERSION
✖ Failed to compile llama.cpp
node-llama-cpp build

Compile the currently downloaded llama.cpp

Options:
  -h, --help        Show help                                                              [boolean]
  -a, --arch        The architecture to compile llama.cpp for                               [string]
  -t, --nodeTarget  The Node.js version to compile llama.cpp for. Example: v18.0.0          [string]
      --metal       Compile llama.cpp with Metal support. Can also be set via the NODE_LLAMA_CPP_MET
                    AL environment variable                               [boolean] [default: false]
      --cuda        Compile llama.cpp with CUDA support. Can also be set via the NODE_LLAMA_CPP_CUDA
                     environment variable                                 [boolean] [default: false]
  -v, --version     Show version number                                                    [boolean]

Error: "/root/.npm/_npx/bd61418a9647e51e/node_modules/node-llama-cpp/llama/llama.cpp" directory does not exist
    at compileLlamaCpp (file:///root/.npm/_npx/bd61418a9647e51e/node_modules/node-llama-cpp/dist/utils/compileLLamaCpp.js:13:19)
    at async file:///root/.npm/_npx/bd61418a9647e51e/node_modules/node-llama-cpp/dist/cli/commands/BuildCommand.js:47:9
    at async withOra (file:///root/.npm/_npx/bd61418a9647e51e/node_modules/node-llama-cpp/dist/utils/withOra.js:6:21)
    at async Object.BuildLlamaCppCommand [as handler] (file:///root/.npm/_npx/bd61418a9647e51e/node_modules/node-llama-cpp/dist/cli/commands/BuildCommand.js:42:5)
root@981b3099966c:/app# 
```

It seems to search the default location under `npx`...

**Comment by giladgd** [comment]
@loretoparisi Your use of the CLI is incorrect and inconsistent with the documentation.

From the documentation:
> ```
>       --release          The tag of the llama.cpp release to download. Set to "latest" to download t
>                          he latest release. Can also be set via the NODE_LLAMA_CPP_REPO_RELEASE envi
>                          ronment variable                               [string] [default: "latest"]
> ```

The `NODE_LLAMA_CPP_REPO_RELEASE` environment variable can be set to the GitHub release of `llama.cpp` you want `node-llama-cpp` to download and compile. You can visit [the releases page of `llama.cpp`](https://github.com/ggerganov/llama.cpp/releases) to find the list of available releases.

Also, you shouldn't use the `build` command as you don't have any release downloaded, so you should use the `download` command instead.

If you'd like to force a download and compilation of `llama.cpp` from source, then you should just do `npx node-llama-cpp download`, but when you run `npm install` in a project that uses `node-llama-cpp`, it'll automatically do this for you when needed, so manually doing this is redundant.

Also, if there is a pre-compiled binary of `llama.cpp` available for your platform and node version, it won't compile anything and instead use the pre-compiled binaries.

**Comment by loretoparisi** [comment]
Yes thank you very much, my aim was to use your great Node wrapper only, not the downloading, tags or release management part.


> @loretoparisi Your use of the CLI is incorrect and inconsistent with the documentation.
> 
> 
> 
> From the documentation:
> 
> > ```
> 
> >       --release          The tag of the llama.cpp release to download. Set to "latest" to download t
> 
> >                          he latest release. Can also be set via the NODE_LLAMA_CPP_REPO_RELEASE envi
> 
> >                          ronment variable                               [string] [default: "latest"]
> 
> > ```
> 
> 
> 
> The `NODE_LLAMA_CPP_REPO_RELEASE` environment variable can be set to the GitHub release of `llama.cpp` you want `node-llama-cpp` to download and compile. You can visit [the releases page of `llama.cpp`](https://github.com/ggerganov/llama.cpp/releases) to find the list of available releases.
> 
> 
> 
> Also, you shouldn't use the `build` command as you don't have any release downloaded, so you should use the `download` command instead.
> 
> 
> 
> If you'd like to force a download and compilation of `llama.cpp` from source, then you should just do `npx node-llama-cpp download`, but when you run `npm install` in a project that uses `node-llama-cpp`, it'll automatically do this for you when needed, so manually doing this is redundant.
> 
> 
> 
> Also, if there is a pre-compiled binary of `llama.cpp` available for your platform and node version, it won't compile anything and instead use the pre-compiled binaries.
