### ISSUE TITLE
Prefix of function call problem

### ISSUE THREAD

**Issue by SusanDoggie** [withcatai/node-llama-cpp#267]
https://github.com/withcatai/node-llama-cpp/blob/c2e322cd9b1707846d147109c0462f59e9c63755/src/chatWrappers/Llama3ChatWrapper.ts#L214

Should this line change to `Note that the ||call: prefix is mandatory`

The bot always omit the `call:` after the `||` token. If I correct this line, the results will be more promising.

**Comment by giladgd** [comment]
I had a different typo that caused this behavior; I'll release a new version soon with the fix.
From my tests, repeating the instruction to use the full `||call:` more often doesn't achieve the desired behavior than just assuring it that `||` is part of the actual call syntax and is not just for demonstration purposes.
