### ISSUE TITLE
Common JS Support 

### ISSUE THREAD

**Issue by sooraj007** [withcatai/node-llama-cpp#281]
### Issue description

Please add support for common js with typescript or please help how to make it work 

### Expected Behavior

Hi, is there any way this library support common js , i have an existing project which is typescript so when is try to use this its throwing error like dynamic import not supported etc,
please help me out

### Actual Behavior

Common js not supported

### Steps to reproduce

Trying to use with common js typescript project existing one

### My Environment

| Dependency               | Version             |
| ---                      | ---                 |
| Operating System         |                     |
| CPU                      | Intel i9 / Apple M1 |
| Node.js version          | x.y.zzz             |
| Typescript version       | x.y.zzz             |
| `node-llama-cpp` version | x.y.zzz             |

### Relevant Features Used

- [ ] Metal support
- [X] CUDA support
- [ ] Grammar

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, and I know how to start.

**Comment by giladgd** [comment]
I don't plan to add support for CommonJS, as it'll make it much more complicated to maintain and develop, and ESM is the official way forward in nodejs.

I've explained it more in depth and provided workarounds for using `node-llama-cpp` in CommonJS projects [here](https://github.com/withcatai/node-llama-cpp/issues/100#issuecomment-1817688891).
