### ISSUE TITLE
Make Chat History optional

### ISSUE THREAD

**Issue by sooraj007** [withcatai/node-llama-cpp#288]
### Feature Description

Hi can you implement an option to make the chat history optional, so if we don't want to keep chat history, and option to disable chat history.

### The Solution

a flag to make enable disable chat history

### Considered Alternatives

So currently iam building an application where chat history is not needed in that scenario , currently there is no option for as temporary work around what can i do clear chat history. please let me know

### Related Features to This Feature Request

- [ ] Metal support
- [X] CUDA support
- [ ] Grammar

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, and I know how to start.

**Comment by giladgd** [comment]
You can reset a chat session after every prompt to keep it clean this way:
```typescript
import {fileURLToPath} from "url";
import path from "path";
import {getLlama, LlamaChatSession} from "node-llama-cpp";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const chatHistoryFilePath = path.join(__dirname, "chatHistory.json");

const llama = await getLlama();
const model = await llama.loadModel({
    modelPath: path.join(__dirname, "models", "dolphin-2.1-mistral-7b.Q4_K_M.gguf")
});
const context = await model.createContext();
const chatSession = new LlamaChatSession({
    contextSequence: context.getSequence()
});

// save the initial chat history
const cleanChatHistory = chatSession.getChatHistory();


const q1 = "Hi there, how are you?";
console.log("User: " + q1);

const a1 = await chatSession.prompt(q1);
console.log("AI: " + a1);

// reset the chat history to the initial state
chatSession.setChatHistory(cleanChatHistory);



const q2 = "What did I just ask you?";
console.log("User: " + q2);

const a2 = await chatSession.prompt(q2);
console.log("AI: " + a2);

// reset the chat history to the initial state
chatSession.setChatHistory(cleanChatHistory);
```

I'll consider making it easier to prompt a model without saving it to the chat history.
My main reason for not doing that is that it may encourage people to do things in a way that then makes it harder to use other features that need a state, such as prompting the model for different response formats of the last response in follow-up prompts.
Having a simple stateless prompt function and integrating it through the codebase may add friction when people need to use more advanced features that do need a state, and having people use a stateful chat session and resetting it will probably make it easier to transition to use it statefully when needed.
I'll make sure to add this code example to the upcoming documentation of version 3.

What do you think?

**Comment by sooraj007** [comment]
thanks expecting the updated documentation is there any eta for the updated documentation,  that would be really awesome , thanks for your help and also good job

**Comment by giladgd** [comment]
@sooraj007 I haven't had enough free time lately to progress with it as much as I planned, but I hope to release it in the next month or so.
