### ISSUE TITLE
Token Info Provider

### ISSUE THREAD

**Issue by sooraj007** [withcatai/node-llama-cpp#289]
### Feature Description

Hi is there any inbuild method or functions to get the total tokens set, tokens remaining, token speed

so can you implement a small method to get all the the above info that would be great

### The Solution

in some scenarios it would be great if we get all these info 

### Considered Alternatives

If its time consuming to implement from your side can you please help me. according to existing implementation how can i able to get these info.

### Related Features to This Feature Request

- [ ] Metal support
- [X] CUDA support
- [ ] Grammar

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, and I know how to start.

**Comment by giladgd** [comment]
I'm not sure I understand what you're asking for.
To get the token utilization of the current context window you can get the index of the next token cell by accessing `contextSequence.nextTokenIndex` and the total tokens that can be fitted in the context window are `context.contextSize`.
You can calculate the speed of generation by using the `onToken` option and checking how fast it generates new tokens.
You can use `contextSequence.tokenMeter.usedOutputTokens` to get the total generated tokens (not only the ones that are user-facing); this is useful for more precise speed calculations.

**Comment by sooraj007** [comment]
Thanks for the help, i guess the above info will do, once the updated documentation put, will get all the api's right. waiting for the updated documentation. thanks
