### ISSUE TITLE
I cannot build my Typescript project when using v3.0.0

### ISSUE THREAD

**Issue by vlamanna** [withcatai/node-llama-cpp#349]
### Issue description

I cannot build my Typescript project when using v3.0.0

### Expected Behavior

My project build.

### Actual Behavior

I'm getting the following error:
```
node_modules/node-llama-cpp/dist/chatWrappers/Llama3_1ChatWrapper.d.ts:12:72 - error TS2339: Property '_specialTokensTextForPreamble' does not exist on type '{ cuttingKnowledgeDate?: string | number | Date | (() => Date) | null | undefined; todayDate?: string | number | Date | (() => Date) | null | undefined; noToolInstructions?: boolean | undefined; }'.

12     constructor({ cuttingKnowledgeDate, todayDate, noToolInstructions, _specialTokensTextForPreamble }?: {
```

It was fine when I was using the beta version.

### Steps to reproduce

- Install package in a Typescript project
- Build the project

### My Environment

| Dependency               | Version             |
| ---                      | ---                 |
| Operating System         | MacOS                    |
| CPU                      | Apple M1 |
| Node.js version          | 20.16.0             |
| Typescript version       | 5.5.2             |
| `node-llama-cpp` version | 3.0.0             |

### Additional Context

I have a PR ready that I will push shortly.

### Relevant Features Used

- [ ] Metal support
- [ ] CUDA support
- [ ] Vulkan support
- [ ] Grammar
- [ ] Function calling

### Are you willing to resolve this issue by submitting a Pull Request?

Yes, I have the time, and I know how to start.

**Comment by giladgd** [comment]
@vlamanna I fixed the issue you're facing in #351 by making sure that `_specialTokensTextForPreamble` will not appear in the transpiled ts types.

However, I couldn't reproduce this issue on my machine.
Scaffolding a project using the `npm create node-llama-cpp@latest` command works on my machine and runs as expected.
Even calling `npx tsc` works as expected.

Can you please share with me what's your `tsconfig.json`?
If you can figure out what's different between your project and the scaffolded project from the `npm create node-llama-cpp@latest` command that causes this issue, it would be very helpful for me so I can add some kind of safeguards to ensure this doesn't happen again.
