### ISSUE TITLE
Settings and how we can control them to the API

### ISSUE THREAD

**Issue by tigert2173** [withcatai/node-llama-cpp#352]
### Feature Description

I'm finding it very difficult to figure out the settings I can and cannot modify, I know I can do temperature but I am also aware of the many others but do not know how they are called for this. If we had a list of these it would help so we don't have to test over and over to see if it's making any difference or if we even got the right name for the setting

### The Solution

Documentation on the possible settings we can change with an json api request and the best ways to do so.

### Considered Alternatives

Not that I know of.

### Related Features to This Feature Request

- [ ] Metal support
- [ ] CUDA support
- [ ] Grammar

### Are you willing to resolve this issue by submitting a Pull Request?

No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by giladgd** [comment]
You can inspect the types of options for every object and function you create to control all the settings.
Each option has a detailed documentation explaining what it does and how to use it.
You can see those types both in TypeScript types of function usages in your project, and on the documentation website.

For example, you can see the options for:
* [`getLlama(...)`](https://node-llama-cpp.withcat.ai/api/functions/getLlama) ([options](https://node-llama-cpp.withcat.ai/api/type-aliases/LlamaChatSessionOptions))
* Llama: [`.loadModel(...)`](https://node-llama-cpp.withcat.ai/api/classes/Llama#loadmodel) ([options](https://node-llama-cpp.withcat.ai/api/type-aliases/LlamaModelOptions))
* LlamaModel: [`.createContext(...)`](https://node-llama-cpp.withcat.ai/api/classes/LlamaModel#createcontext) ([options](https://node-llama-cpp.withcat.ai/api/type-aliases/LlamaContextOptions))
* LlamaChatSession: [constructor](https://node-llama-cpp.withcat.ai/api/classes/LlamaChatSession#new-llamachatsession) ([options](https://node-llama-cpp.withcat.ai/api/type-aliases/LlamaChatSessionOptions)), [`.prompt()`](https://node-llama-cpp.withcat.ai/api/classes/LlamaChatSession#prompt) ([options](https://node-llama-cpp.withcat.ai/api/type-aliases/LLamaChatPromptOptions))

**Comment by tigert2173** [comment]
https://node-llama-cpp.withcat.ai/api/type-aliases/LLamaChatPromptOptions

Thanks found it :D
